// <auto-generated />
using System;
using GerenciamentoFutebolAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoFutebolAPI_Completo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("GerenciamentoFutebolAPI.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("Posicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = 1.76,
                            DataNascimento = new DateTime(2000, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Vinicius Junior",
                            NumeroCamisa = 7,
                            Peso = 73.0,
                            Posicao = "Atacante",
                            Time = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            Altura = 1.74,
                            DataNascimento = new DateTime(2001, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rodrygo",
                            NumeroCamisa = 11,
                            Peso = 68.0,
                            Posicao = "Atacante",
                            Time = "Real Madrid"
                        },
                        new
                        {
                            Id = 3,
                            Altura = 1.75,
                            DataNascimento = new DateTime(2006, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Endrick",
                            NumeroCamisa = 9,
                            Peso = 73.0,
                            Posicao = "Atacante",
                            Time = "Real Madrid"
                        },
                        new
                        {
                            Id = 4,
                            Altura = 1.75,
                            DataNascimento = new DateTime(1992, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Neymar",
                            NumeroCamisa = 10,
                            Peso = 69.0,
                            Posicao = "Atacante",
                            Time = "Al-Hilal"
                        },
                        new
                        {
                            Id = 5,
                            Altura = 1.8500000000000001,
                            DataNascimento = new DateTime(1992, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Casemiro",
                            NumeroCamisa = 5,
                            Peso = 84.0,
                            Posicao = "Volante",
                            Time = "Manchester United"
                        },
                        new
                        {
                            Id = 6,
                            Altura = 1.9099999999999999,
                            DataNascimento = new DateTime(1992, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Alisson",
                            NumeroCamisa = 1,
                            Peso = 91.0,
                            Posicao = "Goleiro",
                            Time = "Liverpool"
                        },
                        new
                        {
                            Id = 7,
                            Altura = 1.8600000000000001,
                            DataNascimento = new DateTime(1998, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Éder Militão",
                            NumeroCamisa = 3,
                            Peso = 78.0,
                            Posicao = "Zagueiro",
                            Time = "Real Madrid"
                        },
                        new
                        {
                            Id = 8,
                            Altura = 1.8200000000000001,
                            DataNascimento = new DateTime(1997, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Bruno Guimarães",
                            NumeroCamisa = 39,
                            Peso = 74.0,
                            Posicao = "Meio-campo",
                            Time = "Newcastle"
                        },
                        new
                        {
                            Id = 9,
                            Altura = 1.76,
                            DataNascimento = new DateTime(1996, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Raphinha",
                            NumeroCamisa = 11,
                            Peso = 68.0,
                            Posicao = "Atacante",
                            Time = "Barcelona"
                        },
                        new
                        {
                            Id = 10,
                            Altura = 1.8400000000000001,
                            DataNascimento = new DateTime(1991, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Danilo",
                            NumeroCamisa = 6,
                            Peso = 78.0,
                            Posicao = "Lateral",
                            Time = "Juventus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
