// <auto-generated />
using System;
using GerenciamentoFutebolAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoFutebolAPI_Final.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("GerenciamentoFutebolAPI.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = new DateTime(2000, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Vinicius Junior",
                            NumeroCamisa = 7,
                            Posicao = "Atacante",
                            Time = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = new DateTime(2001, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rodrygo",
                            NumeroCamisa = 11,
                            Posicao = "Atacante",
                            Time = "Real Madrid"
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = new DateTime(2006, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Endrick",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            Time = "Palmeiras"
                        },
                        new
                        {
                            Id = 4,
                            DataNascimento = new DateTime(1992, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Neymar",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            Time = "Al-Hilal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
